In [18]:
import pandas as pd

cpr_info_df = pd.read_csv('data/TC_EN_NCR_CPR_INFO.csv')

In [20]:
# cpr_info_df.drop(cpr_info_df.tail(1).index,inplace=True) # drop last n rows
cpr_info_df

,STDR_YM,CTPRVN_NM,SIGNGU_NM,ADSTRD_NM,INDUTY_LCLAS_CODE,INDUTY_MLSFC_CODE,INDUTY_LCLAS_NM,INDUTY_MLSFC_NM,SEXDSTN_CODE,SEXDSTN,AGRDE_CODE,AGRDE,NCR_CPR_CO,CAPL_AVRG_AM,REGIST_DE,OPERTOR_NM
0,2011-01,충남,천안시 서북구,성정2동,J,J63,정보통신업,정보서비스업,M,남성,40,40대,1.0,50000000.0,2019-10-19,KEDSYS
1,2011-01,충남,천안시 서북구,성정2동,L,L68,부동산업,부동산업,M,남성,60,60대,1.0,30000000.0,2019-10-19,KEDSYS
2,2011-01,대전,동구,용전동,C,C14,제조업,의복; 의복 액세서리 및 모피제품 제조업,M,남성,40,40대,1.0,50000000.0,2019-10-19,KEDSYS
3,2011-01,대전,동구,용전동,L,L68,부동산업,부동산업,M,남성,50,50대,1.0,100000000.0,2019-10-19,KEDSYS
4,2011-01,대전,동구,용전동,S,S96,협회 및 단체; 수리 및 기타 개인 서비스업,기타 개인 서비스업,M,남성,40,40대,1.0,20000000.0,2019-10-19,KEDSYS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555859,2017-12,서울,영등포구,양평1동,J,J59,정보통신업,영상ㆍ오디오 기록물 제작 및 배급업,M,남성,40,40대,1.0,10000000.0,2019-10-19,KEDSYS
555860,2017-12,서울,영등포구,양평1동,K,K66,금융 및 보험업,금융 및 보험 관련 서비스업,M,남성,40,40대,1.0,10000000.0,2019-10-19,KEDSYS
555861,2018-01,경기,오산시,초평동,C,C20,제조업,화학물질 및 화학제품 제조업; 의약품 제외,M,남성,50,50대,1.0,50000000.0,2019-10-26,KEDSYS
555862,2018-01,경기,오산시,초평동,C,C30,제조업,자동차 및 트레일러 제조업,F,여성,30,30대,1.0,104000000.0,2019-10-26,KEDSYS
555863,2018-01,경기,오산시,초평동,F,F41,건설업,종합 건설업,M,남성,20,20대,1.0,30000000.0,2019-10-26,KEDSYS

In [229]:
cpr_info_df['INDUTY_LCLAS_NM'].value_counts()

제조업                                 124091
도매 및 소매업                            105358
건설업                                  54639
부동산업                                 46383
전문 과학 및 기술 서비스업                      42467
정보통신업                                38770
농업 임업 및 어업                           27006
사업시설 관리 사업 지원 및 임대 서비스업              25872
협회 및 단체 수리 및 기타 개인 서비스업              20891
금융 및 보험업                             14085
운수 및 창고업                             13931
교육 서비스업                               9637
숙박 및 음식점업                             9467
전기 가스 증기 및 공기조절 공급업                   8275
예술 스포츠 및 여가관련 서비스업                    6037
수도 하수 및 폐기물 처리 원료 재생업                 3917
보건업 및 사회복지 서비스업                       3215
광업                                    1717
공공행정 국방 및 사회보장 행정                       65
국제 및 외국기관                               32
가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산활동         9
Name: INDUTY_LCLAS_NM, dtype: int64

In [234]:
cpr_info_df.loc[cpr_info_df['INDUTY_LCLAS_NM'] == '제조업', 'SIGNGU_NM'].value_counts()

화성시        5409
강남구        3964
서구         3190
시흥시        2872
안산시 단원구    2656
           ...
화천군          20
청송군          20
옹진군          12
영양군          12
울릉군           7
Name: SIGNGU_NM, Length: 227, dtype: int64

In [164]:
cpr_info_df.drop(['NCR_CPR_CO'], axis='columns', inplace=True)
cpr_info_df.head()

KeyError: "['NCR_CPR_CO'] not found in axis"

In [135]:
induty_list = ['정보통신업', '부동산업', '제조업', '협회 및 단체 수리 및 기타 개인 서비스업', '도매 및 소매업',
       '건설업', '운수 및 창고업', '사업시설 관리 사업 지원 및 임대 서비스업', '전문 과학 및 기술 서비스업',
       '금융 및 보험업', '교육 서비스업', '농업 임업 및 어업', '보건업 및 사회복지 서비스업',
       '수도 하수 및 폐기물 처리 원료 재생업', '예술 스포츠 및 여가관련 서비스업', '숙박 및 음식점업', '광업',
       '전기 가스 증기 및 공기조절 공급업', '공공행정 국방 및 사회보장 행정',
       '가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산활동', '국제 및 외국기관', '기타']

In [21]:
rm_data = cpr_info_df['INDUTY_LCLAS_NM']
rm_data = rm_data.str.replace(pat=';', repl= r'', regex=False)  # replace multiple spaces with a single space
cpr_info_df['INDUTY_LCLAS_NM'] = rm_data
cpr_info_df

,STDR_YM,CTPRVN_NM,SIGNGU_NM,ADSTRD_NM,INDUTY_LCLAS_CODE,INDUTY_MLSFC_CODE,INDUTY_LCLAS_NM,INDUTY_MLSFC_NM,SEXDSTN_CODE,SEXDSTN,AGRDE_CODE,AGRDE,NCR_CPR_CO,CAPL_AVRG_AM,REGIST_DE,OPERTOR_NM
0,2011-01,충남,천안시 서북구,성정2동,J,J63,정보통신업,정보서비스업,M,남성,40,40대,1.0,50000000.0,2019-10-19,KEDSYS
1,2011-01,충남,천안시 서북구,성정2동,L,L68,부동산업,부동산업,M,남성,60,60대,1.0,30000000.0,2019-10-19,KEDSYS
2,2011-01,대전,동구,용전동,C,C14,제조업,의복; 의복 액세서리 및 모피제품 제조업,M,남성,40,40대,1.0,50000000.0,2019-10-19,KEDSYS
3,2011-01,대전,동구,용전동,L,L68,부동산업,부동산업,M,남성,50,50대,1.0,100000000.0,2019-10-19,KEDSYS
4,2011-01,대전,동구,용전동,S,S96,협회 및 단체 수리 및 기타 개인 서비스업,기타 개인 서비스업,M,남성,40,40대,1.0,20000000.0,2019-10-19,KEDSYS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555859,2017-12,서울,영등포구,양평1동,J,J59,정보통신업,영상ㆍ오디오 기록물 제작 및 배급업,M,남성,40,40대,1.0,10000000.0,2019-10-19,KEDSYS
555860,2017-12,서울,영등포구,양평1동,K,K66,금융 및 보험업,금융 및 보험 관련 서비스업,M,남성,40,40대,1.0,10000000.0,2019-10-19,KEDSYS
555861,2018-01,경기,오산시,초평동,C,C20,제조업,화학물질 및 화학제품 제조업; 의약품 제외,M,남성,50,50대,1.0,50000000.0,2019-10-26,KEDSYS
555862,2018-01,경기,오산시,초평동,C,C30,제조업,자동차 및 트레일러 제조업,F,여성,30,30대,1.0,104000000.0,2019-10-26,KEDSYS
555863,2018-01,경기,오산시,초평동,F,F41,건설업,종합 건설업,M,남성,20,20대,1.0,30000000.0,2019-10-26,KEDSYS

In [27]:
cpr_info_df['INDUTY_LCLAS_NM'].unique()

array(['정보통신업', '부동산업', '제조업', '협회 및 단체 수리 및 기타 개인 서비스업', '도매 및 소매업',
       '건설업', '운수 및 창고업', '사업시설 관리 사업 지원 및 임대 서비스업', '전문 과학 및 기술 서비스업',
       '금융 및 보험업', '교육 서비스업', '농업 임업 및 어업', '보건업 및 사회복지 서비스업',
       '수도 하수 및 폐기물 처리 원료 재생업', '예술 스포츠 및 여가관련 서비스업', '숙박 및 음식점업', '광업',
       '전기 가스 증기 및 공기조절 공급업', '공공행정 국방 및 사회보장 행정',
       '가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산활동', '국제 및 외국기관'], dtype=object)

In [4]:
del(temp_df)
temp_df = cpr_info_df
temp_df
# temp_df['INDUTY_LCLAS_NM'].unique()

NameError: name 'temp_df' is not defined

In [22]:
cpr_info_df['INDUTY_LCLAS_NM'] = cpr_info_df['INDUTY_LCLAS_NM'].fillna('기타')

In [25]:
cpr_info_df['INDUTY_LCLAS_NM'].unique()

array(['정보통신업', '부동산업', '제조업', '협회 및 단체 수리 및 기타 개인 서비스업', '도매 및 소매업',
       '건설업', '운수 및 창고업', '사업시설 관리 사업 지원 및 임대 서비스업', '전문 과학 및 기술 서비스업',
       '금융 및 보험업', '교육 서비스업', '농업 임업 및 어업', '보건업 및 사회복지 서비스업',
       '수도 하수 및 폐기물 처리 원료 재생업', '예술 스포츠 및 여가관련 서비스업', '숙박 및 음식점업', '광업',
       '전기 가스 증기 및 공기조절 공급업', '공공행정 국방 및 사회보장 행정',
       '가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산활동', '국제 및 외국기관'], dtype=object)

In [26]:
import datetime

now = datetime.datetime.now()
now_datetime = now.strftime('%Y%m%d_%H%M')

cpr_info_df.to_csv(f'data/{now_datetime}_TC_EN_NCR_CPR_INFO.csv')